SELECT
EKI.JUSHOCD1,
EKI.EKICD,
EKI.EKINM,
EKI.KUSITU_YM,
EKI.BOSYU_SOUSU,
BK.BOSYU_SOUSU BOSYU_SOUSU_OLD,
decode(EKI.BFLG,1,'データ少',2,'変動大','') 募集数変動,
ROUND(EKI.AVG_TINRYO) AVG_TINRYO,
ROUND(BK.AVG_TINRYO) AVG_TINRYO_OLD,
decode(EKI.TFLG,1,'データ少',2,'変動大','') 賃料変動,
EKI.TOUROKUYMD,
EKI.KOUSINYMD
FROM 
TS_KUSITURITU_EKI EKI,
TS_KUSITURITU_EKI_BK BK
WHERE
EKI.JUSHOCD1 = BK.JUSHOCD1
AND
EKI.EKICD = BK.EKICD
AND
EKI.EKINM = BK.EKINM
AND
EKI.TATEMONO_SYUBETU = BK.TATEMONO_SYUBETU
AND
EKI.MADORI = BK.MADORI
AND
(EKI.BFLG > 0 or EKI.SFLG > 0 or EKI.TFLG > 0)
/

