DROP TABLE TS_KUSITURITU_EKI
/
CREATE TABLE TS_KUSITURITU_EKI (
     EKICD         VARCHAR2(5)   NOT NULL
    ,EKINM         VARCHAR2(64)  NOT NULL
    ,JUSHOCD1      CHAR(2)       NOT NULL
    ,KUSITU_YM     DATE          NOT NULL
    ,SO_KOSU_SOUSU NUMBER
    ,BOSYU_SOUSU   NUMBER        NOT NULL
    ,AVG_TINRYO    NUMBER        NOT NULL
    ,TATEMONO_SYUBETU    VARCHAR2(64)
    ,MADORI               VARCHAR2(10)
    ,TOUROKUYMD    DATE          DEFAULT SYSDATE
    ,KOUSINYMD     DATE          DEFAULT SYSDATE
	,PRIMARY KEY(EKICD,JUSHOCD1,KUSITU_YM,TATEMONO_SYUBETU,MADORI)
)
/
