CREATE TABLE TS_SETUBI_NEEDS_SUM
AS
select
			TS_TATEMONO.JUSHOCD1,
			TS_TATEMONO.JUSHOCD2,
			TS_TATEMONO.TATEMONO_SYUBETU,
			TS_HEYA.MADORI,
			SUM(TS_HEYA_SETUBI.SETUBI026) AIR_CON,
			SUM(TS_HEYA_SETUBI.SETUBI018) SEP_BATH,
			SUM(TS_HEYA_SETUBI.SETUBI006) GAS_STOVE,
			SUM(TS_HEYA_SETUBI.SETUBI037) CLOSET,
			SUM(TS_HEYA_SETUBI.SETUBI017) IND_SINK,
			SUM(TS_HEYA_SETUBI.SETUBI049) AUTO_LOCK,
			SUM(TS_HEYA_SETUBI.SETUBI022) TV_INTER_PHONE,
			SUM(TS_HEYA_SETUBI.SETUBI020) WASHING_TOILET,
			SUM(TS_HEYA_SETUBI.SETUBI012) BATH_DRYER,
			SUM(TS_HEYA_SETUBI.SETUBI016) WASHING_MACHINE_BATH,
			SUM(TS_HEYA_SETUBI.SETUBI059) BALCONY,
			SUM(TS_HEYA_SETUBI.SETUBI043) EV,
			SUM(TS_HEYA_SETUBI.SETUBI024) DELIVERY_BOX,
			SUM(TS_HEYA_SETUBI.SETUBI038) UNDER_FLOOR,
			SUM(TS_HEYA_SETUBI.SETUBI047) DUST_COL,
			SUM(TS_HEYA_SETUBI.SETUBI046) BICYCLE_PARKING,
			SUM(TS_HEYA_SETUBI.SETUBI066) OPTICAL_FIBER,
			SUM(TS_HEYA_SETUBI.SETUBI011) REHEAT,
			SUM(TS_HEYA_SETUBI.SETUBI015) SHAMPOO_DRESSER,
			SUM(TS_HEYA_SETUBI.SETUBI033) FLOORING,
			SUM(TS_HEYA_SETUBI.SETUBI036) WALK_IN_CLOSET,
			SUM(TS_HEYA_SETUBI.SETUBI029) FLOOR_HEAT,
			SUM(TS_HEYA_SETUBI.SETUBI003) IH_COOKINGHEATER,
			SUM(TS_HEYA_SETUBI.SETUBI041) ALL_ELECTRIC,
			SUM(TS_HEYA_SETUBI.SETUBI060) VERANDA,
			SUM(TS_HEYA_SETUBI.SETUBI001) SYSTEM_KITCHEN,
			SUM(TS_HEYA_SETUBI.SETUBI064) CATV,
			SUM(TS_HEYA_SETUBI.SETUBI057) LOFT,
			COUNT(*) CNT
			FROM TS_HEYA_SETUBI,TS_TATEMONO,TS_HEYA
			where
			TS_HEYA_SETUBI.TATEMONO_CD = TS_TATEMONO.TATEMONO_CD
			AND TS_HEYA.TATEMONO_CD = TS_TATEMONO.TATEMONO_CD
			AND TS_HEYA_SETUBI.TOIAWASE_NO = TS_TATEMONO.TOIAWASE_NO
			AND TS_HEYA.TOIAWASE_NO = TS_TATEMONO.TOIAWASE_NO
			AND TS_HEYA.ROOMNO = TS_HEYA_SETUBI.ROOMNO
			AND TS_HEYA.PRIORITY=1
			AND
			months_between(sysdate,TS_TATEMONO.kansei_ymd) >= 36
			AND
			(TS_HEYA_SETUBI.tatemono_cd,TS_HEYA_SETUBI.toiawase_no,TS_HEYA_SETUBI.roomno) 
			in 
			(
				select
						tatemono_cd,
						toiawase_no,
						roomno
				from ts_heya_tinryo_his
				where start_flg != '1'
						and start_flg != '1'
						and tinryo_his_ymd = to_date('&&THIS_KYOKYU_YMD', 'yyyymmdd')
			)
				group by
					TS_TATEMONO.JUSHOCD1,
					TS_TATEMONO.JUSHOCD2,
					TS_TATEMONO.TATEMONO_SYUBETU,
					TS_HEYA.MADORI
/
