REM
REM =head1 NAME 
REM
REM cr_ts_heya_need_sum.sql
REM
REM =head1 DESCRIPTION
REM 
REM 設備情報を直近の供給データから算出する
REM 算出したデータをTS_SETUBI_NEEDS_SUMテーブルに保存。（都度作成するので事前にＤＲＯＰ）
REM
REM =head1 HISTORY
REM
REM =over 4
REM
REM =item 2010/10/25 M.TAKIUCHI CREATED
REM
REM =item 2010/10/25 M.TAKIUCHI COMMENT ADD FOR POD
REM
REM =back
REM
REM =head1 Trouble Shooting
REM
REM テーブルをドロップして何度も再実行可能
REM
REM =head1 AUTHOR
REM 
REM システム部　瀧内誠(mtakiuc@kantei.co.jp)
REM
REM =cut
REM
DROP TABLE TS_SETUBI_NEEDS_SUM
/
CREATE TABLE TS_SETUBI_NEEDS_SUM
AS
select
			SUM.JUSHOCD1,
			SUM.JUSHOCD2,
			SUM.TATEMONO_SYUBETU,
			SUM.MADORI,
			SUM(SUM.SETUBI026) AIR_CON,
			SUM(SUM.SETUBI018) SEP_BATH,
			SUM(SUM.SETUBI005) GAS_STOVE,
			SUM(SUM.SETUBI037) CLOSET,
			SUM(SUM.SETUBI017) IND_SINK,
			SUM(SUM.SETUBI049) AUTO_LOCK,
			SUM(SUM.SETUBI022) TV_INTER_PHONE,
			SUM(SUM.SETUBI020) WASHING_TOILET,
			SUM(SUM.SETUBI012) BATH_DRYER,
			SUM(SUM.SETUBI016) WASHING_MACHINE_BATH,
			SUM(SUM.SETUBI059) BALCONY,
			SUM(SUM.SETUBI043) EV,
			SUM(SUM.SETUBI024) DELIVERY_BOX,
			SUM(SUM.SETUBI038) UNDER_FLOOR,
			SUM(SUM.SETUBI047) DUST_COL,
			SUM(SUM.SETUBI045) BICYCLE_PARKING,
			SUM(SUM.SETUBI066) OPTICAL_FIBER,
			SUM(SUM.SETUBI011) REHEAT,
			SUM(SUM.SETUBI015) SHAMPOO_DRESSER,
			SUM(SUM.SETUBI033) FLOORING,
			SUM(SUM.SETUBI036) WALK_IN_CLOSET,
			SUM(SUM.SETUBI029) FLOOR_HEAT,
			SUM(SUM.SETUBI003) IH_COOKINGHEATER,
			SUM(SUM.SETUBI041) ALL_ELECTRIC,
			SUM(SUM.SETUBI060) VERANDA,
			SUM(SUM.SETUBI001) SYSTEM_KITCHEN,
			SUM(SUM.SETUBI064) CATV,
			SUM(SUM.SETUBI057) LOFT,
			COUNT(*) CNT
			FROM TS_HEYA_TINRYO_HIS_SUM SUM
			where  months_between(to_date('&&THIS_KYOKYU_YMD','YYYYMMDD'),kansei_ymd) <= 36
			and end_flg='0'
			AND exclusion = '0'
			group by
					SUM.JUSHOCD1,
					SUM.JUSHOCD2,
					SUM.TATEMONO_SYUBETU,
					SUM.MADORI
/
