CREATE TABLE TS_SETUBI_NEEDS_SUM
TABLESPACE TSP_SSD
AS
select
			TS_TATEMONO.JUSHOCD1,
			TS_TATEMONO.JUSHOCD2,
			TS_TATEMONO.TATEMONO_SYUBETU,
			TS_HEYA.MADORI,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI026)/COUNT(*)*100) AIR_CON,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI018)/COUNT(*)*100) SEP_BATH,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI006)/COUNT(*)*100) GAS_STOVE,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI037)/COUNT(*)*100) CLOSET,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI017)/COUNT(*)*100) IND_SINK,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI049)/COUNT(*)*100) AUTO_LOCK,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI022)/COUNT(*)*100) TV_INTER_PHONE,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI020)/COUNT(*)*100) WASHING_TOILET,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI012)/COUNT(*)*100) BATH_DRYER,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI016)/COUNT(*)*100) WASHING_MACHINE_BATH,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI059)/COUNT(*)*100) BALCONY,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI043)/COUNT(*)*100) EV,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI024)/COUNT(*)*100) DELIVERY_BOX,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI038)/COUNT(*)*100) UNDER_FLOOR,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI047)/COUNT(*)*100) DUST_COL,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI046)/COUNT(*)*100) BICYCLE_PARKING,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI066)/COUNT(*)*100) OPTICAL_FIBER,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI011)/COUNT(*)*100) REHEAT,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI015)/COUNT(*)*100) SHAMPOO_DRESSER,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI033)/COUNT(*)*100) FLOORING,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI036)/COUNT(*)*100) WALK_IN_CLOSET,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI029)/COUNT(*)*100) FLOOR_HEAT,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI003)/COUNT(*)*100) IH_COOKINGHEATER,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI041)/COUNT(*)*100) ALL_ELECTRIC,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI060)/COUNT(*)*100) VERANDA,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI001)/COUNT(*)*100) SYSTEM_KITCHEN,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI064)/COUNT(*)*100) CATV,
			ROUND(SUM(TS_HEYA_SETUBI.SETUBI057)/COUNT(*)*100) LOFT
			FROM TS_HEYA_SETUBI,TS_TATEMONO,TS_HEYA
			where
			TS_HEYA_SETUBI.TATEMONO_CD = TS_TATEMONO.TATEMONO_CD
			AND TS_HEYA.TATEMONO_CD = TS_TATEMONO.TATEMONO_CD
			AND TS_HEYA_SETUBI.TOIAWASE_NO = TS_TATEMONO.TOIAWASE_NO
			AND TS_HEYA.TOIAWASE_NO = TS_TATEMONO.TOIAWASE_NO
			AND TS_HEYA.ROOMNO = TS_HEYA_SETUBI.ROOMNO
			AND TS_TATEMONO.PRIORITY=1
			AND
			months_between(sysdate,TS_TATEMONO.kansei_ymd) >= 36
			AND
			(TS_HEYA_SETUBI.tatemono_cd,TS_HEYA_SETUBI.toiawase_no,TS_HEYA_SETUBI.roomno) 
			in 
			(
				select
						tatemono_cd,
						toiawase_no,
						roomno
				from ts_heya_tinryo_his
				where start_flg != '1'
						and start_flg != '1'
						and tinryo_his_ymd = to_date('&&THIS_KYOKYU_YMD', 'yyyymmdd')
			)
				group by
					TS_TATEMONO.JUSHOCD1,
					TS_TATEMONO.JUSHOCD2,
					TS_TATEMONO.TATEMONO_SYUBETU,
					TS_HEYA.MADORI
/
REM CREATE INDEX TS_NEED_SUM_JUSHOCD ON TS_SETUBI_NEEDS_SUM(JUSHOCD1,JUSHOCD2);
REM CREATE INDEX TS_NEED_SUM_TSYUBETU ON TS_SETUBI_NEEDS_SUM(TATEMONO_SYUBETU);
REM CREATE INDEX TS_NEED_SUM_MADORI ON TS_SETUBI_NEEDS_SUM(MADORI);
