REM EXEC USING OSSUSR FOR KANTEI SCHEMA
CREATE SYNONYM TS_TATEMONO FOR KANTEI.TS_TATEMONO;
CREATE SYNONYM TS_TATEMONO_DTL FOR KANTEI.TS_TATEMONO_DTL;
CREATE SYNONYM TS_HEYA FOR KANTEI.TS_HEYA;
CREATE SYNONYM TS_HEYA_DTL FOR KANTEI.TS_HEYA_DTL;
CREATE SYNONYM TS_HEYA_CYUSYA FOR KANTEI.TS_HEYA_CYUSYA;
CREATE SYNONYM TS_HEYA_SETUBI FOR KANTEI.TS_HEYA_SETUBI;
CREATE SYNONYM TS_HEYA_TINRYO FOR KANTEI.TS_HEYA_TINRYO;
CREATE SYNONYM TS_HEYA_TINRYO_BK FOR KANTEI.TS_HEYA_TINRYO_BK;
CREATE SYNONYM TS_HEYA_TINRYO_HIS FOR KANTEI.TS_HEYA_TINRYO_HIS;
CREATE SYNONYM TS_HEYA_TINRYO_HIS_SUM FOR KANTEI.TS_HEYA_TINRYO_HIS_SUM;
CREATE SYNONYM TS_KUSITURITU_JU FOR KANTEI.TS_KUSITURITU_JU;
CREATE SYNONYM TS_KUSITURITU_EKI FOR KANTEI.TS_KUSITURITU_EKI;
CREATE SYNONYM TS_OWNER_TATEMONO FOR KANTEI.TS_OWNER_TATEMONO;
CREATE SYNONYM TS_SETUBI_NEEDS FOR KANTEI.TS_SETUBI_NEEDS;
