-- 建物マスタ（仮）
CREATE TABLE TS_TATEMONO (
     TATEMONO_CD         VARCHAR2(20)  NOT NULL
    ,TOIAWASE_NO         VARCHAR2(20)  NOT NULL
    ,KYOKYU_CD           VARCHAR2(2)   NOT NULL
    ,JUSHOCD1            CHAR(2)       NOT NULL
    ,JUSHOCD2            CHAR(3)       NOT NULL
    ,JUSHOCD3            CHAR(3)       NOT NULL
    ,JUSHOCD4            CHAR(3)       NOT NULL
    ,YUBIN_NO            CHAR(7)
    ,TATEMONO_SYUBETU_NM VARCHAR2(64)  NOT NULL
    ,TATEMONO_SYUBETU    VARCHAR2(64)
    ,KOZO_SYUBETU_NM     VARCHAR2(64)  NOT NULL
    ,KOZO_SYUBETU        VARCHAR2(64)
    ,SO_KAISU            NUMBER(2)
    ,CHIKA_KAISU         NUMBER(2)
    ,TATEMONO_M2         NUMBER
    ,SIKITI_M2           NUMBER
    ,SO_KOSU             NUMBER(4)
    ,KANSEI_YMD          DATE
    ,TOUROKUYMD          DATE          DEFAULT SYSDATE
    ,PRIORITY                   NUMBER         DEFAULT 0 NOT NULL
    ,KOUSINYMD           DATE          DEFAULT SYSDATE
    ,PRIMARY KEY(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD)
)
/

-- 建物詳細マスタ（仮）
CREATE TABLE TS_TATEMONO_DTL (
     TATEMONO_CD            VARCHAR2(20)   NOT NULL
    ,TOIAWASE_NO            VARCHAR2(20)   NOT NULL
    ,KYOKYU_CD              VARCHAR2(2)    NOT NULL
    ,BUKKEN_NM              VARCHAR2(200)
    ,JUSHO_NM               VARCHAR2(128)
    ,JUSHONM1               VARCHAR2(8)
    ,JUSHONM2               VARCHAR2(24)
    ,JUSHONM3               VARCHAR2(36)
    ,JUSHONM4               VARCHAR2(24)
    ,CHIBAN                 VARCHAR2(80)
    ,AABSX                  NUMBER(8)
    ,AABSY                  NUMBER(8)
    ,IDO                    NUMBER(10)
    ,KEIDO                  NUMBER(10)
    ,IDO_WGS                NUMBER(10)
    ,KEIDO_WGS              NUMBER(10)
    ,TOCHI_M2               NUMBER
    ,TOCHI_TUBO             NUMBER
    ,YOTO_CHIKI             VARCHAR2(24)
    ,SYAKUCHIKEN_SYURUI     VARCHAR2(24)
    ,EKI_CD1                VARCHAR2(10)
    ,ENSEN_CD1              VARCHAR2(5)
    ,EKI_NM1                VARCHAR2(64)
    ,ENSEN_NM1              VARCHAR2(64)
    ,EKI_BUS_KAISYA_NM1     VARCHAR2(64)
    ,EKI_BUS_JIKAN1         NUMBER(4)
    ,EKI_BUSTEI_NM1         VARCHAR2(50)
    ,EKI_TOHO_JIKAN1        NUMBER(4)
    ,EKI_BUSTEI_TOHO_JIKAN1 NUMBER(4)
    ,EKI_KURUMA_JIKAN1      NUMBER(4)
    ,EKI_KYORI1             NUMBER
    ,EKI_CD2                VARCHAR2(10)
    ,ENSEN_CD2              VARCHAR2(5)
    ,EKI_NM2                VARCHAR2(64)
    ,ENSEN_NM2              VARCHAR2(64)
    ,EKI_BUS_KAISYA_NM2     VARCHAR2(64)
    ,EKI_BUS_JIKAN2         NUMBER(4)
    ,EKI_BUSTEI_NM2         VARCHAR2(50)
    ,EKI_TOHO_JIKAN2        NUMBER(4)
    ,EKI_BUSTEI_TOHO_JIKAN2 NUMBER(4)
    ,EKI_KURUMA_JIKAN2      NUMBER(4)
    ,EKI_KYORI2             NUMBER
    ,EKI_CD3                VARCHAR2(10)
    ,ENSEN_CD3              VARCHAR2(5)
    ,EKI_NM3                VARCHAR2(64)
    ,ENSEN_NM3              VARCHAR2(64)
    ,EKI_BUS_KAISYA_NM3     VARCHAR2(64)
    ,EKI_BUS_JIKAN3         NUMBER(4)
    ,EKI_BUSTEI_NM3         VARCHAR2(50)
    ,EKI_TOHO_JIKAN3        NUMBER(4)
    ,EKI_BUSTEI_TOHO_JIKAN3 NUMBER(4)
    ,BUS_KAISYA_NM1         VARCHAR2(64)
    ,BUSTEI_NM1             VARCHAR2(30)
    ,BUSTEI_TOHO_JIKAN1     NUMBER(4)
    ,BUS_KAISYA_NM2         VARCHAR2(64)
    ,BUSTEI_NM2             VARCHAR2(30)
    ,BUSTEI_TOHO_JIKAN2     NUMBER(4)
    ,BUS_KAISYA_NM3         VARCHAR2(64)
    ,BUSTEI_NM3             VARCHAR2(30)
    ,BUSTEI_TOHO_JIKAN3     NUMBER(4)
    ,YOTIEN_NM              VARCHAR2(128)
    ,YOTIEN_KYORI           NUMBER(5)
    ,HOIKUEN_NM             VARCHAR2(128)
    ,HOIKUEN_KYORI          VARCHAR2(5)
    ,SYOGAKKO_NM            VARCHAR2(128)
    ,SYOGAKKO_KYORI         VARCHAR2(5)
    ,CYUGAKKO_NM            VARCHAR2(128)
    ,CYUGAKKO_KYORI         VARCHAR2(5)
    ,KOKO_NM                VARCHAR2(128)
    ,KOKO_KYORI             VARCHAR2(5)
    ,DAIGAKU_NM             VARCHAR2(128)
    ,DAIGAKU_KYORI          VARCHAR2(5)
    ,BYOIN_NM               VARCHAR2(128)
    ,BYOIN_KYORI            VARCHAR2(5)
    ,SUPER_NM               VARCHAR2(128)
    ,SUPER_KYORI            VARCHAR2(5)
    ,KONBINI_NM             VARCHAR2(128)
    ,KONBINI_KYORI          VARCHAR2(5)
    ,TOUROKUYMD             DATE           DEFAULT SYSDATE
    ,KOUSINYMD              DATE           DEFAULT SYSDATE
    ,PRIMARY KEY(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD)
)
/

-- 部屋マスタ（仮）
CREATE TABLE TS_HEYA (
     TATEMONO_CD        VARCHAR2(20)   NOT NULL
    ,TOIAWASE_NO        VARCHAR2(20)   NOT NULL
    ,KYOKYU_CD          VARCHAR2(2)    NOT NULL
    ,ROOMNO             VARCHAR2(10)   NOT NULL
    ,HEYA_NM            VARCHAR2(120)
    ,KAI                NUMBER(2)
    ,MADORI_NM          VARCHAR2(10)   NOT NULL
    ,MADORI             VARCHAR2(10)
    ,MADORI_BIKO        VARCHAR2(256)
    ,HOGAKU_NM          VARCHAR2(4)
    ,SENYU_M2           NUMBER
    ,BARUKONI_M2        NUMBER
    ,SINTIKU_FLG        CHAR(1)
    ,IPPAN_KOKAI_FLG    CHAR(1)
    ,KEIYAKU_KEITAI_KBN CHAR(1)
    ,KUSITU_JOKYO_KBN   CHAR(1)
    ,NYUKYO_KANO_YM     DATE
    ,KUSITU_CHK_YMD     DATE
    ,TOUROKUYMD         DATE           DEFAULT SYSDATE
    ,KOUSINYMD          DATE           DEFAULT SYSDATE
    ,PRIMARY KEY(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO)
)
/

-- 間取詳細（仮）
CREATE TABLE TS_HEYA_DTL (
     TATEMONO_CD        VARCHAR2(20)  NOT NULL
    ,TOIAWASE_NO        VARCHAR2(20)  NOT NULL
    ,KYOKYU_CD          VARCHAR2(2)   NOT NULL
    ,ROOMNO             VARCHAR2(10)  NOT NULL
    ,MADORI_DTL_NM1     VARCHAR2(10)
    ,MADORI_DTL_JYOSU1  NUMBER
    ,MADORI_DTL_NM2     VARCHAR2(10)
    ,MADORI_DTL_JYOSU2  NUMBER
    ,MADORI_DTL_NM3     VARCHAR2(10)
    ,MADORI_DTL_JYOSU3  NUMBER
    ,MADORI_DTL_NM4     VARCHAR2(10)
    ,MADORI_DTL_JYOSU4  NUMBER
    ,MADORI_DTL_NM5     VARCHAR2(10)
    ,MADORI_DTL_JYOSU5  NUMBER
    ,MADORI_DTL_NM6     VARCHAR2(10)
    ,MADORI_DTL_JYOSU6  NUMBER
    ,MADORI_DTL_NM7     VARCHAR2(10)
    ,MADORI_DTL_JYOSU7  NUMBER
    ,MADORI_DTL_NM8     VARCHAR2(10)
    ,MADORI_DTL_JYOSU8  NUMBER
    ,MADORI_DTL_NM9     VARCHAR2(10)
    ,MADORI_DTL_JYOSU9  NUMBER
    ,MADORI_DTL_NM10    VARCHAR2(10)
    ,MADORI_DTL_JYOSU10 NUMBER
    ,MADORI_DTL_NM11    VARCHAR2(10)
    ,MADORI_DTL_JYOSU11 NUMBER
    ,MADORI_DTL_NM12    VARCHAR2(10)
    ,MADORI_DTL_JYOSU12 NUMBER
    ,TOUROKUYMD         DATE          DEFAULT SYSDATE
    ,KOUSINYMD          DATE          DEFAULT SYSDATE
    ,PRIMARY KEY(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO)
)
/

-- 駐車場マスタ（仮）
CREATE TABLE TS_HEYA_CYUSYA (
     TATEMONO_CD                  VARCHAR2(20)   NOT NULL
    ,TOIAWASE_NO                  VARCHAR2(20)   NOT NULL
    ,KYOKYU_CD                    VARCHAR2(2)    NOT NULL
    ,ROOMNO                       VARCHAR2(10)   NOT NULL
    ,CYUSYAJO                     VARCHAR2(10)
    ,CYUSYA_RYO                   NUMBER(8)
    ,CYUSYA_RYO_ZEI               NUMBER(8)
    ,CYUSYA_SIKIKIN_HYOJI         VARCHAR2(6)
    ,CYUSYA_SIKIKIN               NUMBER(8)
    ,CYUSYA_SIKIKIN_TUKI_SU       NUMBER
    ,CYUSYA_KOSINRYO              NUMBER(8)
    ,CYUSYA_KOSINRYO_TUKI_SU      NUMBER
    ,CYUSYA_KOSINRYO_ZEI          NUMBER(8)
    ,CYUSYAJO_BIKO                VARCHAR2(256)
    ,CYUSYA_KANO_DAISU            NUMBER(2)
    ,CYUSYA_SYOKAI_RYO            NUMBER(8)
    ,CYUSYA_SYOKAI_RYO_ZEI        NUMBER(8)
    ,CYUSYA_REIKIN_HYOJI          VARCHAR2(6)
    ,CYUSYA_REIKIN                NUMBER(8)
    ,CYUSYA_REIKIN_TUKI_SU        NUMBER
    ,CYUSYA_REIKIN_ZEI            NUMBER(8)
    ,CYUSYA_KOSIN_TESURYO         NUMBER(8)
    ,CYUSYA_KOSIN_TESURYO_TUKI_SU NUMBER
    ,CYUSYA_KOSIN_TESURYO_ZEI     NUMBER(8)
    ,TOUROKUYMD                   DATE           DEFAULT SYSDATE
    ,KOUSINYMD                    DATE           DEFAULT SYSDATE
    ,PRIMARY KEY(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO)
)
/

-- 設備マスタ（仮）
CREATE TABLE TS_HEYA_SETUBI (
     TATEMONO_CD           VARCHAR2(20)   NOT NULL
    ,TOIAWASE_NO           VARCHAR2(20)   NOT NULL
    ,KYOKYU_CD             VARCHAR2(2)    NOT NULL
    ,ROOMNO                VARCHAR2(10)   NOT NULL
    ,SETUBI_CNT            NUMBER
    ,SETUBI_WEIGHT         NUMBER
    ,SETUBI001             CHAR(1)
    ,SETUBI002             CHAR(1)
    ,SETUBI003             CHAR(1)
    ,SETUBI004             CHAR(1)
    ,SETUBI005             CHAR(1)
    ,SETUBI006             CHAR(1)
    ,SETUBI007             CHAR(1)
    ,SETUBI008             CHAR(1)
    ,SETUBI009             CHAR(1)
    ,SETUBI010             CHAR(1)
    ,SETUBI011             CHAR(1)
    ,SETUBI012             CHAR(1)
    ,SETUBI013             CHAR(1)
    ,SETUBI014             CHAR(1)
    ,SETUBI015             CHAR(1)
    ,SETUBI016             CHAR(1)
    ,SETUBI017             CHAR(1)
    ,SETUBI018             CHAR(1)
    ,SETUBI019             CHAR(1)
    ,SETUBI020             CHAR(1)
    ,SETUBI021             CHAR(1)
    ,SETUBI022             CHAR(1)
    ,SETUBI023             CHAR(1)
    ,SETUBI024             CHAR(1)
    ,SETUBI025             CHAR(1)
    ,SETUBI026             CHAR(1)
    ,SETUBI027             CHAR(1)
    ,SETUBI028             CHAR(1)
    ,SETUBI029             CHAR(1)
    ,SETUBI030             CHAR(1)
    ,SETUBI031             CHAR(1)
    ,SETUBI032             CHAR(1)
    ,SETUBI033             CHAR(1)
    ,SETUBI034             CHAR(1)
    ,SETUBI035             CHAR(1)
    ,SETUBI036             CHAR(1)
    ,SETUBI037             CHAR(1)
    ,SETUBI038             CHAR(1)
    ,SETUBI039             CHAR(1)
    ,SETUBI040             CHAR(1)
    ,SETUBI041             CHAR(1)
    ,SETUBI042             CHAR(1)
    ,SETUBI043             CHAR(1)
    ,SETUBI044             CHAR(1)
    ,SETUBI045             CHAR(1)
    ,SETUBI046             CHAR(1)
    ,SETUBI047             CHAR(1)
    ,SETUBI048             CHAR(1)
    ,SETUBI049             CHAR(1)
    ,SETUBI050             CHAR(1)
    ,SETUBI051             CHAR(1)
    ,SETUBI052             CHAR(1)
    ,SETUBI053             CHAR(1)
    ,SETUBI054             CHAR(1)
    ,SETUBI055             CHAR(1)
    ,SETUBI056             CHAR(1)
    ,SETUBI057             CHAR(1)
    ,SETUBI058             CHAR(1)
    ,SETUBI059             CHAR(1)
    ,SETUBI060             CHAR(1)
    ,SETUBI061             CHAR(1)
    ,SETUBI062             CHAR(1)
    ,SETUBI063             CHAR(1)
    ,SETUBI064             CHAR(1)
    ,SETUBI065             CHAR(1)
    ,SETUBI066             CHAR(1)
    ,SETUBI067             CHAR(1)
    ,SETUBI068             CHAR(1)
    ,SETUBI069             CHAR(1)
    ,SETUBI070             CHAR(1)
    ,SETUBI071             CHAR(1)
    ,INYOSUI_SETUBI_SYURUI VARCHAR2(14)
    ,INYOSUI_SETUBI        VARCHAR2(160)
    ,DENKI_SETUBI          VARCHAR2(160)
    ,GAS_SETUBI_SYURUI     VARCHAR2(8)
    ,GAS_SETUBI            VARCHAR2(160)
    ,HAISUI_SETUBI         VARCHAR2(100)
    ,SETUBI_BIKO           VARCHAR2(256)
    ,TOUROKUYMD            DATE           DEFAULT SYSDATE
    ,KOUSINYMD             DATE           DEFAULT SYSDATE
    ,PRIMARY KEY(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO)
)
/

-- 賃料マスタ（仮）
CREATE TABLE TS_HEYA_TINRYO (
     TATEMONO_CD                VARCHAR2(20)   NOT NULL
    ,TOIAWASE_NO                VARCHAR2(20)   NOT NULL
    ,KYOKYU_CD                  VARCHAR2(2)    NOT NULL
    ,ROOMNO                     VARCHAR2(10)   NOT NULL
    ,TINSYAKU_KEITAI_KBN        VARCHAR2(10)
    ,TINRYO                     NUMBER(8)      NOT NULL
    ,TINRYO_ZEI                 NUMBER(8)
    ,KANRIHI                    NUMBER(8)
    ,KANRIHI_ZEI                NUMBER(8)
    ,KYOEKIHI                   NUMBER(8)
    ,KYOEKIHI_ZEI               NUMBER(8)
    ,SIKIKIN_HYOJI              VARCHAR2(6)
    ,SIKIKIN                    NUMBER(8)
    ,SIKIKIN_TUKI_SU            NUMBER
    ,SYOKYAKU                   VARCHAR2(6)
    ,SYOKYAKUKIN                NUMBER(8)
    ,SYOKYAKUKIN_TUKI_SU        NUMBER
    ,SYOKYAKUKIN_RITU           NUMBER
    ,REIKIN_HYOJI               VARCHAR2(6)
    ,REIKIN                     NUMBER(8)
    ,REIKIN_TUKI_SU             NUMBER
    ,REIKIN_ZEI                 NUMBER(8)
    ,KOSINRYO_UMU               VARCHAR2(4)
    ,KOSINRYO                   NUMBER(8)
    ,KOSINRYO_TUKI_SU           NUMBER
    ,KOSINRYO_ZEI               NUMBER(8)
    ,KOSIN_JIMU_TESURYO         NUMBER(8)
    ,KOSIN_JIMU_TESURYO_TUKI_SU NUMBER
    ,KOSIN_JIMU_TESURYO_ZEI     NUMBER(8)
    ,JUTAKU_HOKEN_UMU           VARCHAR2(4)
    ,JUTAKU_HOKENRYO            NUMBER(8)
    ,JUTAKU_HOKENRYO_ZEI        NUMBER(8)
    ,HOSYONIN_HITUYO            VARCHAR2(4)
    ,SUIDO_KONETUHI             VARCHAR2(4)
    ,CYOKAIHI                   NUMBER(8)
    ,CYOKAIHI_ZEI               NUMBER(8)
    ,HIYO_INI1_NM               VARCHAR2(100)
    ,HIYO_INI1                  NUMBER(8)
    ,HIYO_INI1_ZEI              NUMBER(8)
    ,HIYO_INI2_NM               VARCHAR2(100)
    ,HIYO_INI2                  NUMBER(8)
    ,HIYO_INI2_ZEI              NUMBER(8)
    ,HIYO_INI3_NM               VARCHAR2(100)
    ,HIYO_INI3                  NUMBER(8)
    ,HIYO_INI3_ZEI              NUMBER(8)
    ,HIYO_M1_NM                 VARCHAR2(100)
    ,HIYO_M1                    NUMBER(8)
    ,HIYO_M1_ZEI                NUMBER(8)
    ,HIYO_M2_NM                 VARCHAR2(100)
    ,HIYO_M2                    NUMBER(8)
    ,HIYO_M2_ZEI                NUMBER(8)
    ,HIYO_M3_NM                 VARCHAR2(100)
    ,HIYO_M3                    NUMBER(8)
    ,HIYO_M3_ZEI                NUMBER(8)
    ,HIYO_BIKO                  VARCHAR2(256)
    ,PET_KANO_FLG               CHAR(1)
    ,GAKKI_KANO_FLG             CHAR(1)
    ,JIMUSYO_KANO_FLG           CHAR(1)
    ,KODOMO_KANO_FLG            CHAR(1)
    ,HOJIN_GENTEI_FLG           CHAR(1)
    ,JOSEI_GENTEI_FLG           CHAR(1)
    ,KOREISYA_MUKE_FLG          CHAR(1)
    ,TANSINSYA_FUKA_FLG         CHAR(1)
    ,SONOTA_NYUKYO_JOKEN        VARCHAR2(60)
    ,TOKUYAKU                   VARCHAR2(500)
    ,TIN_BIKO                   VARCHAR2(256)
    ,PR_CMT1                    VARCHAR2(30)
    ,PR_CMT2                    VARCHAR2(60)
    ,EXCLUSION                  CHAR(1)        DEFAULT 0 NOT NULL
    ,PRIORITY                   NUMBER         DEFAULT 0 NOT NULL
    ,PRIORITY_SELECT            CHAR(1)        DEFAULT 0 NOT NULL
    ,KITEN_TOUROKUYMD           DATE
    ,KYOKYU_YMD                 DATE           NOT NULL
    ,INITIAL_YMD                DATE
    ,DOWN_YMD                   DATE
    ,TOUROKUYMD                 DATE           DEFAULT SYSDATE
    ,KOUSINYMD                  DATE           DEFAULT SYSDATE
    ,PRIMARY KEY(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO,TINRYO,KYOKYU_YMD)
)
/

-- 賃料バックアップ（仮）
CREATE TABLE TS_HEYA_TINRYO_BK (
     TATEMONO_CD                VARCHAR2(20)   NOT NULL
    ,TOIAWASE_NO                VARCHAR2(20)   NOT NULL
    ,KYOKYU_CD                  VARCHAR2(2)    NOT NULL
    ,ROOMNO                     VARCHAR2(10)   NOT NULL
    ,TINSYAKU_KEITAI_KBN        VARCHAR2(10)
    ,TINRYO                     NUMBER(8)      NOT NULL
    ,TINRYO_ZEI                 NUMBER(8)
    ,KANRIHI                    NUMBER(8)
    ,KANRIHI_ZEI                NUMBER(8)
    ,KYOEKIHI                   NUMBER(8)
    ,KYOEKIHI_ZEI               NUMBER(8)
    ,SIKIKIN_HYOJI              VARCHAR2(6)
    ,SIKIKIN                    NUMBER(8)
    ,SIKIKIN_TUKI_SU            NUMBER
    ,SYOKYAKU                   VARCHAR2(6)
    ,SYOKYAKUKIN                NUMBER(8)
    ,SYOKYAKUKIN_TUKI_SU        NUMBER
    ,SYOKYAKUKIN_RITU           NUMBER
    ,REIKIN_HYOJI               VARCHAR2(6)
    ,REIKIN                     NUMBER(8)
    ,REIKIN_TUKI_SU             NUMBER
    ,REIKIN_ZEI                 NUMBER(8)
    ,KOSINRYO_UMU               VARCHAR2(4)
    ,KOSINRYO                   NUMBER(8)
    ,KOSINRYO_TUKI_SU           NUMBER
    ,KOSINRYO_ZEI               NUMBER(8)
    ,KOSIN_JIMU_TESURYO         NUMBER(8)
    ,KOSIN_JIMU_TESURYO_TUKI_SU NUMBER
    ,KOSIN_JIMU_TESURYO_ZEI     NUMBER(8)
    ,JUTAKU_HOKEN_UMU           VARCHAR2(4)
    ,JUTAKU_HOKENRYO            NUMBER(8)
    ,JUTAKU_HOKENRYO_ZEI        NUMBER(8)
    ,HOSYONIN_HITUYO            VARCHAR2(4)
    ,SUIDO_KONETUHI             VARCHAR2(4)
    ,CYOKAIHI                   NUMBER(8)
    ,CYOKAIHI_ZEI               NUMBER(8)
    ,HIYO_INI1_NM               VARCHAR2(100)
    ,HIYO_INI1                  NUMBER(8)
    ,HIYO_INI1_ZEI              NUMBER(8)
    ,HIYO_INI2_NM               VARCHAR2(100)
    ,HIYO_INI2                  NUMBER(8)
    ,HIYO_INI2_ZEI              NUMBER(8)
    ,HIYO_INI3_NM               VARCHAR2(100)
    ,HIYO_INI3                  NUMBER(8)
    ,HIYO_INI3_ZEI              NUMBER(8)
    ,HIYO_M1_NM                 VARCHAR2(100)
    ,HIYO_M1                    NUMBER(8)
    ,HIYO_M1_ZEI                NUMBER(8)
    ,HIYO_M2_NM                 VARCHAR2(100)
    ,HIYO_M2                    NUMBER(8)
    ,HIYO_M2_ZEI                NUMBER(8)
    ,HIYO_M3_NM                 VARCHAR2(100)
    ,HIYO_M3                    NUMBER(8)
    ,HIYO_M3_ZEI                NUMBER(8)
    ,HIYO_BIKO                  VARCHAR2(256)
    ,PET_KANO_FLG               CHAR(1)
    ,GAKKI_KANO_FLG             CHAR(1)
    ,JIMUSYO_KANO_FLG           CHAR(1)
    ,KODOMO_KANO_FLG            CHAR(1)
    ,HOJIN_GENTEI_FLG           CHAR(1)
    ,JOSEI_GENTEI_FLG           CHAR(1)
    ,KOREISYA_MUKE_FLG          CHAR(1)
    ,TANSINSYA_FUKA_FLG         CHAR(1)
    ,SONOTA_NYUKYO_JOKEN        VARCHAR2(60)
    ,TOKUYAKU                   VARCHAR2(500)
    ,TIN_BIKO                   VARCHAR2(256)
    ,PR_CMT1                    VARCHAR2(30)
    ,PR_CMT2                    VARCHAR2(60)
    ,EXCLUSION                  CHAR(1)
    ,PRIORITY                   NUMBER
    ,PRIORITY_SELECT            CHAR(1)
    ,KITEN_TOUROKUYMD           DATE
    ,KYOKYU_YMD                 DATE           NOT NULL
    ,INITIAL_YMD                DATE
    ,DOWN_YMD                   DATE
    ,TOUROKUYMD                 DATE           DEFAULT SYSDATE
    ,KOUSINYMD                  DATE           DEFAULT SYSDATE
    ,PRIMARY KEY(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO,TINRYO,KYOKYU_YMD)
)
/

-- 賃料履歴
CREATE TABLE TS_HEYA_TINRYO_HIS (
     TATEMONO_CD     VARCHAR2(20)  NOT NULL
    ,TOIAWASE_NO     VARCHAR2(20)  DEFAULT 0 NOT NULL
    ,KYOKYU_CD       VARCHAR2(2)   DEFAULT 0 NOT NULL
    ,ROOMNO          VARCHAR2(10)  NOT NULL
    ,TINRYO          NUMBER(8)     DEFAULT 0 NOT NULL
    ,TINRYO_HIS_YMD  DATE          NOT NULL
    ,START_FLG       CHAR(1)       DEFAULT 0 NOT NULL
    ,END_FLG         CHAR(1)       DEFAULT 0 NOT NULL
    ,START_YMD       DATE
    ,START_YMD_SUM   DATE
    ,END_YMD         DATE
    ,END_YMD_SUM     DATE
    ,KANRIHI         NUMBER(8)
    ,KYOEKIHI        NUMBER(8)
    ,SIKIKIN_TUKI_SU NUMBER
    ,REIKIN_TUKI_SU  NUMBER
    ,TINSYAKU_KEITAI_KBN  VARCHAR2(10)
    ,SYOKYAKU                   VARCHAR2(6)
    ,SYOKYAKUKIN                NUMBER(8)
    ,SYOKYAKUKIN_TUKI_SU        NUMBER
    ,KOSINRYO              NUMBER(8)
    ,KOSINRYO_TUKI_SU      NUMBER
    ,TOUROKUYMD      DATE          DEFAULT SYSDATE
    ,KOUSINYMD       DATE          DEFAULT SYSDATE
    ,PRIMARY KEY(TATEMONO_CD,ROOMNO,TINRYO_HIS_YMD,START_FLG,END_FLG)
)
/

-- 賃料履歴サマリ
CREATE TABLE TS_HEYA_TINRYO_HIS_SUM (
     TATEMONO_CD           VARCHAR2(20)  NOT NULL
    ,ROOMNO                VARCHAR2(10)  NOT NULL
    ,END_FLG               CHAR(1)       DEFAULT 0 NOT NULL
    ,START_YMD_SUM         DATE
    ,START_TINRYO          NUMBER(8)
    ,START_KANRIHI         NUMBER(8)
    ,START_KYOEKIHI        NUMBER(8)
    ,START_SIKIKIN_TUKI_SU NUMBER
    ,START_REIKIN_TUKI_SU  NUMBER
    ,END_YMD_SUM           DATE
    ,END_TINRYO            NUMBER(8)
    ,END_KANRIHI           NUMBER(8)
    ,END_KYOEKIHI          NUMBER(8)
    ,END_SIKIKIN_TUKI_SU   NUMBER
    ,END_REIKIN_TUKI_SU    NUMBER
    ,KYOKYU_YMD            DATE
    ,PERIOD                NUMBER
    ,EXCLUSION             CHAR(1)       DEFAULT 0
    ,TINSYAKU_KEITAI_KBN  VARCHAR2(10)
    ,SYOKYAKU                   VARCHAR2(6)
    ,SYOKYAKUKIN                NUMBER(8)
    ,SYOKYAKUKIN_TUKI_SU        NUMBER
    ,KOSINRYO              NUMBER(8)
    ,KOSINRYO_TUKI_SU      NUMBER
    ,TOUROKUYMD            DATE          DEFAULT SYSDATE
    ,KOUSINYMD             DATE          DEFAULT SYSDATE
	,CONSTRAINT PK_SUM PRIMARY KEY(TATEMONO_CD,ROOMNO,END_FLG)
)
/

-- 空室率（行政区）
CREATE TABLE TS_KUSITURITU_JU (
     JUSHOCD1      CHAR(2)       NOT NULL
    ,JUSHOCD2      CHAR(3)
    ,JUSHONM1      VARCHAR2(8)
    ,JUSHONM2      VARCHAR2(24)
    ,KUSITU_YM     DATE          NOT NULL
    ,SO_KOSU_SOUSU NUMBER 
    ,BOSYU_SOUSU   NUMBER        NOT NULL
    ,AVG_TINRYO    NUMBER        NOT NULL
    ,TOUROKUYMD    DATE          DEFAULT SYSDATE
    ,KOUSINYMD     DATE          DEFAULT SYSDATE
    ,CONSTRAINT PK_JU PRIMARY KEY(JUSHOCD1,KUSITU_YM)
)
/
-- 空室率（行政区）
CREATE TABLE TS_KUSITURITU_JU_BK (
     JUSHOCD1      CHAR(2)
    ,JUSHOCD2      CHAR(3)
    ,JUSHONM1      VARCHAR2(8)
    ,JUSHONM2      VARCHAR2(24)
    ,KUSITU_YM     DATE 
    ,TATEMONO_SYUBETU    VARCHAR2(64)
    ,MADORI               VARCHAR2(10)
    ,END_FLG         CHAR(1)       DEFAULT 0 NOT NULL
    ,BOSYU_SOUSU   NUMBER 
	,BFLG                VARCHAR2(1)
	,SFLG                VARCHAR2(1)
	,TFLG                VARCHAR2(1)
    ,TOUROKUYMD    DATE          DEFAULT SYSDATE
    ,KOUSINYMD     DATE          DEFAULT SYSDATE
)
/

-- 空室率（駅）
CREATE TABLE TS_KUSITURITU_EKI (
     EKICD         VARCHAR2(5)  NOT NULL
    ,EKINM         VARCHAR2(64)  NOT NULL
    ,JUSHOCD1      CHAR(2) 
    ,KUSITU_YM     DATE          NOT NULL
    ,SO_KOSU_SOUSU NUMBER
    ,BOSYU_SOUSU   NUMBER        NOT NULL
    ,AVG_TINRYO    NUMBER        NOT NULL
    ,TATEMONO_SYUBETU    VARCHAR2(64)
    ,MADORI               VARCHAR2(10)
    ,TOUROKUYMD    DATE          DEFAULT SYSDATE
    ,KOUSINYMD     DATE          DEFAULT SYSDATE
    ,CONSTRAINT PK_EKI PRIMARY KEY(EKICD,EKINM,KUSITU_YM,TATEMONO_SYUBETU,MADORI)
)
/
-- 空室率（駅）
CREATE TABLE TS_KUSITURITU_EKI_BK (
     EKICD         VARCHAR2(5)  NOT NULL
    ,EKINM         VARCHAR2(64)  NOT NULL
    ,JUSHOCD1      CHAR(2)
    ,KUSITU_YM     DATE          NOT NULL
    ,SO_KOSU_SOUSU NUMBER
    ,BOSYU_SOUSU   NUMBER        NOT NULL
    ,AVG_TINRYO    NUMBER        NOT NULL
    ,TATEMONO_SYUBETU    VARCHAR2(64)
    ,MADORI               VARCHAR2(10)
	,BFLG                VARCHAR2(1)
	,SFLG                VARCHAR2(1)
	,TFLG                VARCHAR2(1)
    ,TOUROKUYMD    DATE          DEFAULT SYSDATE
    ,KOUSINYMD     DATE          DEFAULT SYSDATE
)
/
REM-- 設備ニーズ
REM CREATE TABLE TS_SETUBI_NEEDS (
REM 	JUSHOCD1          CHAR(2)       NOT NULL
REM 	,TATEMONO_SYUBETU    VARCHAR2(64) NOT NULL
REM 	,SINGLE_FAMILY_FLG CHAR(1)       NOT NULL
REM 	,SETUBI            VARCHAR2(64)  NOT NULL
REM 	,PRIORITY          NUMBER        NOT NULL
REM 	,NEEDS             NUMBER        NOT NULL
REM 	,TOUROKUYMD        DATE          DEFAULT SYSDATE
REM 	,KOUSINYMD         DATE          DEFAULT SYSDATE
REM 	,PRIMARY KEY(JUSHOCD1,SINGLE_FAMILY_FLG,SETUBI,TATEMONO_SYUBETU)
REM )

CREATE TABLE TS_SETUBI_NEEDS_SUM2 (
 	JUSHOCD1          CHAR(2)       NOT NULL,
	JUSHOCD2          CHAR(3),
	TATEMONO_SYUBETU  VARCHAR2(64)  NOT NULL,
	SINGLE_FAMILY_FLG CHAR(1)       NOT NULL,
	SETUBI            VARCHAR2(64)  NOT NULL,
	RATE              NUMBER        NOT NULL,
	PRIORITY          NUMBER        NOT NULL,
	NEEDS             NUMBER        NOT NULL,
	TOUROKUYMD        DATE          DEFAULT SYSDATE,
	KOUSINYMD         DATE          DEFAULT SYSDATE,
	CONSTRAINT PK_NSUM2 PRIMARY KEY(JUSHOCD1, TATEMONO_SYUBETU, SINGLE_FAMILY_FLG,SETUBI)
)
/
CREATE TABLE TS_EKI_SRCH 
(	
JUSHOCD1 CHAR(2), 
EKINM VARCHAR2(64), 
EKICD VARCHAR2(5), 
TOIAWASE_NO VARCHAR2(20), 
TATEMONO_CD VARCHAR2(20) NOT NULL ENABLE, 
ROOMNO VARCHAR2(10) NOT NULL ENABLE, 
END_FLG CHAR(1) NOT NULL ENABLE
)
/
CREATE TABLE "TS_SEIYAKU" 
(	"TATEMONO_CD" VARCHAR2(20),
	"ROOMNO" VARCHAR2(10),
	"END_FLG" CHAR(1) DEFAULT 0,
	"START_YMD_SUM" DATE, 
	"START_TINRYO" NUMBER(8,0), 
	"START_KANRIHI" NUMBER(8,0), 
	"START_KYOEKIHI" NUMBER(8,0), 
	"START_SIKIKIN_TUKI_SU" NUMBER, 
	"START_REIKIN_TUKI_SU" NUMBER, 
	"END_YMD_SUM" DATE, 
	"END_TINRYO" NUMBER(8,0), 
	"END_KANRIHI" NUMBER(8,0), 
	"END_KYOEKIHI" NUMBER(8,0), 
	"END_SIKIKIN_TUKI_SU" NUMBER, 
	"END_REIKIN_TUKI_SU" NUMBER, 
	"KYOKYU_YMD" DATE, 
	"PERIOD" NUMBER, 
	"EXCLUSION" CHAR(1) DEFAULT 0, 
	"TINSYAKU_KEITAI_KBN" VARCHAR2(10), 
	"SYOKYAKU" VARCHAR2(6), 
	"SYOKYAKUKIN" NUMBER(8,0), 
	"SYOKYAKUKIN_TUKI_SU" NUMBER, 
	"KOSINRYO" NUMBER(8,0), 
	"KOSINRYO_TUKI_SU" NUMBER, 
	"TOUROKUYMD" DATE DEFAULT SYSDATE, 
	"KOUSINYMD" DATE DEFAULT SYSDATE, 
	"JUSHOCD1" CHAR(2), 
	"JUSHOCD2" CHAR(3), 
	"JUSHOCD3" CHAR(3), 
	"JUSHOCD4" CHAR(3), 
	"JUSHO" VARCHAR2(128), 
	"JUSHONM" VARCHAR2(8), 
	"JUSHONM2" VARCHAR2(24), 
	"JUSHONM3" VARCHAR2(24), 
	"JUSHONM4" VARCHAR2(36), 
	"AABSX" NUMBER(8,0), 
	"AABSY" NUMBER(8,0), 
	"MADORI_NM" VARCHAR2(10), 
	"MADORI" VARCHAR2(10), 
	"TATEMONO_SYUBETU" VARCHAR2(64), 
	"SENYU_M2" NUMBER, 
	"KANSEI_YMD" DATE, 
	"EKI_TOHO_JIKAN1" NUMBER(4,0), 
	"EKI_NM1" VARCHAR2(64), 
	"EKI_TOHO_JIKAN2" NUMBER(4,0), 
	"EKI_NM2" VARCHAR2(64), 
	"EKI_TOHO_JIKAN3" NUMBER(4,0), 
	"EKI_NM3" VARCHAR2(64), 
	"KOZO_SYUBETU" VARCHAR2(64), 
	"KAI" NUMBER(2,0), 
	"SO_KAISU" NUMBER(2,0), 
	"SO_KOSU" NUMBER(4,0), 
	"JUSHO_NM" VARCHAR2(128), 
	"ENSEN_NM1" VARCHAR2(64), 
	"ENSEN_NM2" VARCHAR2(64), 
	"ENSEN_NM3" VARCHAR2(64), 
	"HEYA_NM" VARCHAR2(120), 
	"HOGAKU_NM" VARCHAR2(4), 
	"MADORI_DTL_NM1" VARCHAR2(10), 
	"MADORI_DTL_JYOSU1" NUMBER, 
	"MADORI_DTL_NM2" VARCHAR2(10), 
	"MADORI_DTL_JYOSU2" NUMBER, 
	"MADORI_DTL_NM3" VARCHAR2(10), 
	"MADORI_DTL_JYOSU3" NUMBER, 
	"MADORI_DTL_NM4" VARCHAR2(10), 
	"MADORI_DTL_JYOSU4" NUMBER, 
	"MADORI_DTL_NM5" VARCHAR2(10), 
	"MADORI_DTL_JYOSU5" NUMBER, 
	"MADORI_DTL_NM6" VARCHAR2(10), 
	"MADORI_DTL_JYOSU6" NUMBER, 
	"MADORI_DTL_NM7" VARCHAR2(10), 
	"MADORI_DTL_JYOSU7" NUMBER, 
	"MADORI_DTL_NM8" VARCHAR2(10), 
	"MADORI_DTL_JYOSU8" NUMBER, 
	"MADORI_DTL_NM9" VARCHAR2(10), 
	"MADORI_DTL_JYOSU9" NUMBER, 
	"MADORI_DTL_NM10" VARCHAR2(10), 
	"MADORI_DTL_JYOSU10" NUMBER, 
	"MADORI_DTL_NM11" VARCHAR2(10), 
	"MADORI_DTL_JYOSU11" NUMBER, 
	"MADORI_DTL_NM12" VARCHAR2(10), 
	"MADORI_DTL_JYOSU12" NUMBER, 
	"CYUSYAJO" VARCHAR2(10), 
	"CYUSYA_RYO" NUMBER(8,0), 
	"SETUBI001" CHAR(1), 
	"SETUBI002" CHAR(1), 
	"SETUBI003" CHAR(1), 
	"SETUBI004" CHAR(1), 
	"SETUBI005" CHAR(1), 
	"SETUBI006" CHAR(1), 
	"SETUBI007" CHAR(1), 
	"SETUBI008" CHAR(1), 
	"SETUBI009" CHAR(1), 
	"SETUBI010" CHAR(1), 
	"SETUBI011" CHAR(1), 
	"SETUBI012" CHAR(1), 
	"SETUBI013" CHAR(1), 
	"SETUBI014" CHAR(1), 
	"SETUBI015" CHAR(1), 
	"SETUBI016" CHAR(1), 
	"SETUBI017" CHAR(1), 
	"SETUBI018" CHAR(1), 
	"SETUBI019" CHAR(1), 
	"SETUBI020" CHAR(1), 
	"SETUBI021" CHAR(1), 
	"SETUBI022" CHAR(1), 
	"SETUBI023" CHAR(1), 
	"SETUBI024" CHAR(1), 
	"SETUBI025" CHAR(1), 
	"SETUBI026" CHAR(1), 
	"SETUBI027" CHAR(1), 
	"SETUBI028" CHAR(1), 
	"SETUBI029" CHAR(1), 
	"SETUBI030" CHAR(1), 
	"SETUBI031" CHAR(1), 
	"SETUBI032" CHAR(1), 
	"SETUBI033" CHAR(1), 
	"SETUBI034" CHAR(1), 
	"SETUBI035" CHAR(1), 
	"SETUBI036" CHAR(1), 
	"SETUBI037" CHAR(1), 
	"SETUBI038" CHAR(1), 
	"SETUBI039" CHAR(1), 
	"SETUBI040" CHAR(1), 
	"SETUBI041" CHAR(1), 
	"SETUBI042" CHAR(1), 
	"SETUBI043" CHAR(1), 
	"SETUBI044" CHAR(1), 
	"SETUBI045" CHAR(1), 
	"SETUBI046" CHAR(1), 
	"SETUBI047" CHAR(1), 
	"SETUBI048" CHAR(1), 
	"SETUBI049" CHAR(1), 
	"SETUBI050" CHAR(1), 
	"SETUBI051" CHAR(1), 
	"SETUBI052" CHAR(1), 
	"SETUBI053" CHAR(1), 
	"SETUBI054" CHAR(1), 
	"SETUBI055" CHAR(1), 
	"SETUBI056" CHAR(1), 
	"SETUBI057" CHAR(1), 
	"SETUBI058" CHAR(1), 
	"SETUBI059" CHAR(1), 
	"SETUBI060" CHAR(1), 
	"SETUBI061" CHAR(1), 
	"SETUBI062" CHAR(1), 
	"SETUBI063" CHAR(1), 
	"SETUBI064" CHAR(1), 
	"SETUBI065" CHAR(1), 
	"SETUBI066" CHAR(1), 
	"SETUBI067" CHAR(1), 
	"SETUBI068" CHAR(1), 
	"SETUBI069" CHAR(1), 
	"SETUBI070" CHAR(1), 
	"SETUBI071" CHAR(1), 
	"TOIAWASE_NO" VARCHAR2(20), 
	"KYOKYU_CD" VARCHAR2(2), 
	"SIKIKIN" NUMBER, 
	"EKI_CD1" VARCHAR2(5), 
	"EKI_CD2" VARCHAR2(5), 
	"EKI_CD3" VARCHAR2(5), 
	"EKI_BUS_JIKAN1" NUMBER(4,0), 
	"EKI_BUSTEI_TOHO_JIKAN1" NUMBER(4,0), 
	"EKI_BUS_JIKAN2" NUMBER(4,0), 
	"EKI_BUSTEI_TOHO_JIKAN2" NUMBER(4,0), 
	"EKI_BUS_JIKAN3" NUMBER(4,0), 
	"EKI_BUSTEI_TOHO_JIKAN3" NUMBER(4,0), 
	"BUSTEI_TOHO_JIKAN1" NUMBER(4,0), 
	"BUSTEI_TOHO_JIKAN2" NUMBER(4,0), 
	"BUSTEI_TOHO_JIKAN3" NUMBER(4,0), 
	"START_SIKIKIN" NUMBER, 
	"END_SIKIKIN" NUMBER, 
	"START_REIKIN" NUMBER, 
	"END_REIKIN" NUMBER, 
	"START_SYOKYAKUKIN" NUMBER, 
	"END_SYOKYAKUKIN" NUMBER, 
	"START_SYOKYAKUKIN_TUKI_SU" NUMBER, 
	"END_SYOKYAKUKIN_TUKI_SU" NUMBER, 
	"START_SYOKYAKUKIN_RITU" NUMBER, 
	"END_SYOKYAKUKIN_RITU" NUMBER, 
	"KEIYAKU_KEITAI_KBN" CHAR(1)
)
/

ALTER TABLE TS_TATEMONO_DTL ADD (FOREIGN KEY(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD) REFERENCES TS_TATEMONO(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD))
/
ALTER TABLE TS_HEYA ADD (FOREIGN KEY(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD) REFERENCES TS_TATEMONO(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD))
/
ALTER TABLE TS_HEYA_DTL ADD (FOREIGN KEY(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO) REFERENCES TS_HEYA(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO))
/
ALTER TABLE TS_HEYA_CYUSYA ADD (FOREIGN KEY(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO) REFERENCES TS_HEYA(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO))
/
ALTER TABLE TS_HEYA_SETUBI ADD (FOREIGN KEY(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO) REFERENCES TS_HEYA(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO))
/
ALTER TABLE TS_HEYA_TINRYO ADD (FOREIGN KEY(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO) REFERENCES TS_HEYA(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO))
/
ALTER TABLE TS_HEYA_TINRYO_BK ADD (FOREIGN KEY(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO) REFERENCES TS_HEYA(TATEMONO_CD,TOIAWASE_NO,KYOKYU_CD,ROOMNO))
/
@altertable
@nolloging
@alterekicd
