DROP TABLE TS_HEYA_TINRYO_HIS_SUM
/
-- ’À—¿—š—ðƒTƒ}ƒŠ
CREATE TABLE TS_HEYA_TINRYO_HIS_SUM (
     TATEMONO_CD           VARCHAR2(20)  NOT NULL
    ,ROOMNO                VARCHAR2(10)  NOT NULL
    ,END_FLG               CHAR(1)       DEFAULT 0 NOT NULL
    ,START_YMD_SUM         DATE
    ,START_TINRYO          NUMBER(8)
    ,START_KANRIHI         NUMBER(8)
    ,START_KYOEKIHI        NUMBER(8)
    ,START_SIKIKIN_TUKI_SU NUMBER
    ,START_REIKIN_TUKI_SU  NUMBER
    ,END_YMD_SUM           DATE
    ,END_TINRYO            NUMBER(8)
    ,END_KANRIHI           NUMBER(8)
    ,END_KYOEKIHI          NUMBER(8)
    ,END_SIKIKIN_TUKI_SU   NUMBER
    ,END_REIKIN_TUKI_SU    NUMBER
    ,KYOKYU_YMD            DATE
    ,PERIOD                NUMBER
    ,EXCLUSION             CHAR(1)       DEFAULT 0
    ,TINSYAKU_KEITAI_KBN  VARCHAR2(10)
    ,SYOKYAKU                   VARCHAR2(6)
    ,SYOKYAKUKIN                NUMBER(8)
    ,SYOKYAKUKIN_TUKI_SU        NUMBER
    ,KOSINRYO              NUMBER(8)
    ,KOSINRYO_TUKI_SU      NUMBER
    ,TOUROKUYMD            DATE          DEFAULT SYSDATE
    ,KOUSINYMD             DATE          DEFAULT SYSDATE
    ,PRIMARY KEY(TATEMONO_CD,ROOMNO,END_FLG)
)
TABLESPACE TSP_SSD
/
