REM EXEC USING OSSUSR FOR KANTEI SCHEMA
DROP SYNONYM TS_TATEMONO;
DROP SYNONYM TS_TATEMONO_DTL;
DROP SYNONYM TS_HEYA;
DROP SYNONYM TS_HEYA_DTL;
DROP SYNONYM TS_HEYA_CYUSYA;
DROP SYNONYM TS_HEYA_SETUBI;
DROP SYNONYM TS_HEYA_TINRYO;
DROP SYNONYM TS_HEYA_TINRYO_BK;
DROP SYNONYM TS_HEYA_TINRYO_HIS;
DROP SYNONYM TS_HEYA_TINRYO_HIS_SUM;
DROP SYNONYM TS_KUSITURITU_JU;
DROP SYNONYM TS_KUSITURITU_EKI;
DROP SYNONYM TS_OWNER_TATEMONO;
DROP SYNONYM TS_SETUBI_NEEDS;
