INSERT INTO TS_TATEMONO_DTL (
		TATEMONO_CD
	    ,TOIAWASE_NO
		,KYOKYU_CD
		,BUKKEN_NM
		,JUSHO_NM
		,JUSHONM1
		,JUSHONM2
		,JUSHONM3
		,JUSHONM4
		,CHIBAN
		,IDO_WGS
		,KEIDO_WGS
		,TOCHI_M2
		,TOCHI_TUBO
		,YOTO_CHIKI
		,SYAKUCHIKEN_SYURUI
		,EKI_CD1
		,ENSEN_CD1
		,EKI_NM1
		,ENSEN_NM1
		,EKI_BUS_KAISYA_NM1
		,EKI_BUS_JIKAN1
		,EKI_BUSTEI_NM1
		,EKI_TOHO_JIKAN1
		,EKI_BUSTEI_TOHO_JIKAN1
		,EKI_KURUMA_JIKAN1
		,EKI_KYORI1
		,EKI_CD2
		,ENSEN_CD2
		,EKI_NM2
		,ENSEN_NM2
		,EKI_BUS_KAISYA_NM2
		,EKI_BUS_JIKAN2
		,EKI_BUSTEI_NM2
		,EKI_TOHO_JIKAN2
		,EKI_BUSTEI_TOHO_JIKAN2
		,EKI_KURUMA_JIKAN2
		,EKI_KYORI2
		,EKI_CD3
		,ENSEN_CD3
		,EKI_NM3
		,ENSEN_NM3
		,EKI_BUS_KAISYA_NM3
		,EKI_BUS_JIKAN3
		,EKI_BUSTEI_NM3
		,EKI_TOHO_JIKAN3
		,EKI_BUSTEI_TOHO_JIKAN3
		,BUS_KAISYA_NM1
		,BUSTEI_NM1
		,BUSTEI_TOHO_JIKAN1
		,BUS_KAISYA_NM2
		,BUSTEI_NM2
		,BUSTEI_TOHO_JIKAN2
		,BUS_KAISYA_NM3
		,BUSTEI_NM3
		,BUSTEI_TOHO_JIKAN3
		,YOTIEN_NM
		,YOTIEN_KYORI
		,HOIKUEN_NM
		,HOIKUEN_KYORI
		,SYOGAKKO_NM
		,SYOGAKKO_KYORI
		,CYUGAKKO_NM
		,CYUGAKKO_KYORI
		,KOKO_NM
		,KOKO_KYORI
		,DAIGAKU_NM
		,DAIGAKU_KYORI
		,BYOIN_NM
		,BYOIN_KYORI
		,SUPER_NM
		,SUPER_KYORI
		,KONBINI_NM
		,KONBINI_KYORI
		,TOUROKUYMD
		,KOUSINYMD
		)
		SELECT
		distinct(TATEMONO_CD) tatemono_cd
	    ,TOIAWASE_NO
		,'01' KYOKYU_CD
		,'' BUKKEN_NM
		,JUSYO_NM
		,'' JUSHONM1
		,'' JUSHONM2
		,'' JUSHONM3
		,'' JUSHONM4
		,'' CHIBAN
		,'' IDO_WGS
		,'' KEIDO_WGS
		,'' TOCHI_M2
		,'' TOCHI_TUBO
		,'' YOTO_CHIKI
		,'' SYAKUCHIKEN_SYURUI
		,EKI_CD1
		,ENSEN_CD1
		,EKI_NM1
		,ENSEN_NM1
		,EKI_BUS_KAISYA_NM1
		,EKI_BUS_JIKAN1
		,EKI_BUSTEI_NM1
		,EKI_TOHO_JIKAN1
		,EKI_BUSTEI_TOHO_JIKAN1
		,'' EKI_KURUMA_JIKAN1
		,'' EKI_KYORI1
		,EKI_CD2
		,ENSEN_CD2
		,EKI_NM2
		,ENSEN_NM2
		,EKI_BUS_KAISYA_NM2
		,EKI_BUS_JIKAN2
		,EKI_BUSTEI_NM2
		,EKI_TOHO_JIKAN2
		,EKI_BUSTEI_TOHO_JIKAN2
		,'' EKI_KURUMA_JIKAN2
		,'' EKI_KYORI2
		,EKI_CD3
		,ENSEN_CD3
		,EKI_NM3
		,ENSEN_NM3
		,EKI_BUS_KAISYA_NM3
		,EKI_BUS_JIKAN3
		,EKI_BUSTEI_NM3
		,EKI_TOHO_JIKAN3
		,EKI_BUSTEI_TOHO_JIKAN3
		,BUS_KAISYA_NM1
		,BUSTEI_NM1
		,BUSTEI_TOHO_JIKAN1
		,BUS_KAISYA_NM2
		,BUSTEI_NM2
		,BUSTEI_TOHO_JIKAN2
		,BUS_KAISYA_NM3
		,BUSTEI_NM3
		,BUSTEI_TOHO_JIKAN3
		,YOTIEN_NM
		,YOTIEN_KYORI
		,HOIKUEN_NM
		,HOIKUEN_KYORI
		,SYOGAKKO_NM
		,SYOGAKKO_KYORI
		,CYUGAKKO_NM
		,CYUGAKKO_KYORI
		,KOKO_NM
		,KOKO_KYORI
		,DAIGAKU_NM
		,DAIGAKU_KYORI
		,BYOIN_NM
		,BYOIN_KYORI
		,SUPER_NM
		,SUPER_KYORI
		,KONBINI_NM
		,KONBINI_KYORI
		,sysdate
		,sysdate
		    FROM apawk
		where (tatemono_cd,toiawase_no) not in (select tatemono_cd,toiawase_no from ts_tatemono_dtl
		where apawk.tatemono_cd = ts_tatemono_dtl.tatemono_cd
		and apawk.toiawase_no = ts_tatemono_dtl.toiawase_no
		)
/
