TRUNCATE TABLE TS_ADAM.TS_HEYA_TINRYO_HIS_SUM ;
TRUNCATE TABLE TS_ADAM.TS_KUSITURITU_JU ;
TRUNCATE TABLE TS_ADAM.TS_KUSITURITU_JU_BK ;
TRUNCATE TABLE TS_ADAM.TS_KUSITURITU_EKI ;
TRUNCATE TABLE TS_ADAM.TS_SETUBI_NEEDS_SUM2 ;
